//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipsManagmentProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentInternships = new HashSet<StudentInternship>();
            this.StudentInternships1 = new HashSet<StudentInternship1>();
        }
    
        public string StudentId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string UserId { get; set; }
        public string University { get; set; }
        public string Domain { get; set; }
        public string Bio { get; set; }
        public System.DateTime Birthday { get; set; }
        public string LevelOfStudies { get; set; }
        public Nullable<bool> Available { get; set; }
        public string StudentCV { get; set; }
        public string WebsiteLink { get; set; }
        public string Faculty { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string PhoneNumber { get; set; }
        //i came, i saw no argument for deletin fields, i won by default BOOM inapoi la lista de string-uri BOOM phone number BOOM city
        //comon change it back again i'm ready GRRRR

        public string City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<string> Skills { get; set; }
        public Nullable<bool> Subscribed { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Resume Resume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentInternship> StudentInternships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentInternship1> StudentInternships1 { get; set; }
    }
}
