//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipsManagmentProject.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class StudentInternship
    {
        public string StudentId { get; set; }
        public string InternshipId { get; set; }
        public string StudentUserId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Completed { get; set; }

        [DisplayName("Observatii")]
        public string Updates { get; set; }

        [DisplayName("CV")]
        public string SubmitedResume { get; set; }
        public Nullable<bool> StatusOfApplication { get; set; }
        public string StudentResumeId { get; set; }
        public Nullable<bool> StarredForFurtherReview { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string FileTwo { get; set; }
        public string FileThree { get; set; }
        public string Stage { get; set; }
        public Nullable<bool> Hidden { get; set; }
    
        public virtual File File { get; set; }
        public virtual File File1 { get; set; }
        public virtual Internship Internship { get; set; }
        public virtual Resume Resume { get; set; }
        public virtual Student Student { get; set; }
    }
}
